name: 树洞

register:
  captcha:
    content: "欢迎您注册${name}，您的验证码是${code}，请在${expire}分钟内完成注册。"
    expire: 10 #minutes
  salt: "D779A3049CBC61E938E43EFF2AB026CE"

db:
  mysql:
    account:
      dsn: "root:root@tcp(127.0.0.1:3306)/account?charset=utf8mb4&parseTime=True&loc=Local"
    topic:
      dsn: "root:root@tcp(127.0.0.1:3306)/topic?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    account:
      dsn: "redis://<user>:<password>@<host>:<port>/<db>"
    topic:
      dsn: "redis://<user>:<password>@<host>:<port>/<db>"

token:
  expire: 720 #hours
  secret: "12255C8AA7FAE430EA75181CCF5EE94F"

server:
  gateway:
    host: "localhost"
    port: 8088
  etcd:
    host: "localhost"
    port: 2379
  account:
    host: "localhost"
    port: 8081
  topic:
    host: "localhost"
    port: 8082

email:
  host: "smtp.gmail.com"
  port: 587
  user: "email"
  pass: "password"
  replyTo: "example@gmail.com"
  max: 200

recaptcha: "6jaz0001LcJjGA" #https://www.google.com/recaptcha/admin