// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tid       uint32         `gorm:"column:tid;not null" json:"tid"`
	UID       uint32         `gorm:"column:uid;not null" json:"uid"`
	Content   string         `gorm:"column:content;not null" json:"content"`
	Like      uint32         `gorm:"column:like;not null" json:"like"`
	Root      uint32         `gorm:"column:root" json:"root"`
	ToUID     uint32         `gorm:"column:to_uid" json:"to_uid"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
