// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStar = "star"

// Star mapped from table <star>
type Star struct {
	UID       uint32    `gorm:"column:uid;primaryKey" json:"uid"`
	TopicID   uint32    `gorm:"column:topic_id;primaryKey" json:"topic_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName Star's table name
func (*Star) TableName() string {
	return TableNameStar
}
